spring:
  jackson:
    default-property-inclusion: non_null
  application:
    name: event-ingestion
  main:
    web-application-type: reactive
  devtools:
    restart:
      enabled: true


server:
  port: 8181
retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000

kafka-config:
  bootstrap-servers: ${KAFKA_BROKER_1}:19092, ${KAFKA_BROKER_2}:29092, ${KAFKA_BROKER_3}:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://schema-registry:8081
  topic-name: track-event
  topic-names-to-create:
    - track-event
  num-of-partitions: 3
  replication-factor: 3

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.LongSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  compression-type: snappy
  enable-idempotence: true
  acks: all
  batch-size: 16384
  batch-size-boost-factor: 100
  linger-ms: 5
  request-timeout-ms: 60000
  retry-count: 5

shaft:
  services:
    campaign-url : localhost
