spring:
  elasticsearch:
    uris: ${HOST_NAME:localhost}:9200
    host: ${HOST_NAME:localhost}
    port: 9200
    username: elastic
    password: 5o1NwRcarr=bpvh*kaX8
  jackson:
    default-property-inclusion: non_null
  application:
    name: CART-MANAGEMENT
  main:
    web-application-type: reactive
  devtools:
    restart:
      enabled: true

eureka:
  client:
#    service-url: { defaultZone : http://localhost:8761/eureka/ }
    service-url: { defaultZone: http://discovery-server:8761/eureka/ }
    # TODO service-url: { defaultZone : 'http://' + ${DISCOVERY_SERVER_HOST:localhost} + ":8761/eureka/" }
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
    instance-id: ${spring.application.name}:${random.value}

server:
  port: 8083

logging:
  level:
    root: info

