spring:
  elasticsearch:
    uris: http://localhost:9200
    host: localhost
    port: 9200
    username: elastic
    password: 5o1NwRcarr=bpvh*kaX8
  jackson:
    default-property-inclusion: non_null
  application:
    name: USER-MANAGEMENT
  main:
    web-application-type: reactive
  devtools:
    restart:
      enabled: true

#eureka:
#  clients:
#    service-url: { defaultZone : http://localhost:8761/eureka/ }
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    prefer-ip-address: true
#    lease-expiration-duration-in-seconds: 60
#    lease-renewal-interval-in-seconds: 60
#    instance-id: ${spring.application.name}:${random.value}

server:
  port: 8085

logging:
  level:
    root: info

