version: '1.0'

services:
  app-gateway:
    build:
      context: ../app-gateway
      dockerfile: ../app-gateway/Dockerfile
    hostname: app-gateway
    environment:
      - DISCOVERY_SERVER_HOST=discovery-server
      - REDIS=redis
    image: app-gateway-image:latest
    restart: always
    depends_on:
      - discovery-server
      - redis
    ports:
      - "8080:8080"
    networks:
      - ${GLOBAL_NETWORK}
