version: '1.0'

services:
  cart-management:
    hostname: cart-management
    build:
      context: ../cart-management
      dockerfile: ../cart-management/Dockerfile
    image: cart-management-image:latest
    environment:
      - DISCOVERY_SERVER_HOST=discovery-server
    restart: always
    depends_on:
      - discovery-server
      - app-gateway
    ports:
      - "8083:8083"
    networks:
      - ${GLOBAL_NETWORK}
