version: '1.0'

services:
  marketing-engine:
    hostname: marketing-engine
    build:
      context: ../marketing-engine
      dockerfile: ../marketing-engine/Dockerfile
    image: marketing-engine-image:latest
    environment:
      - DISCOVERY_SERVER_HOST=discovery-server
    restart: always
    depends_on:
      - discovery-server
      - app-gateway
    ports:
      - "8086:8086"
    networks:
      - ${GLOBAL_NETWORK}
