version: '1.0'

services:
  products-catalog:
    hostname: products-catalog
    build:
      context: ../products-catalog
      dockerfile: ../products-catalog/Dockerfile
    image: products-catalog-image:latest
    environment:
      - DISCOVERY_SERVER_HOST=discovery-server
      - HOST_NAME=elastic
      - SPRING_PROFILES_ACTIVE=dev
    restart: always
    depends_on:
      - app-gateway
      - discovery-server
    ports:
      - "8088:8088"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ${GLOBAL_NETWORK}
