version: '1.0'

services:
  products-catalog:
    hostname: products-catalog
    build:
      context: ../products-catalog
      dockerfile: ../products-catalog/Dockerfile
    image: products-catalog-image:latest
    environment:
      - DISCOVERY_SERVER_HOST=discovery-server
    restart: always
#    depends_on:
#      - discovery-server
#      - app-gateway
    ports:
      - "8088:8088"
    networks:
      - ${GLOBAL_NETWORK}
