version: '1.0'

services:
  redis:
    image: redis:6.2-alpine
    hostname: redis
    restart: always
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    ports:
      - 6379:6379
    networks:
      - ${GLOBAL_NETWORK}
