version: '1.0'

services:
  reporting-management:
    hostname: reporting-management
    build:
      context: ../reporting-management
      dockerfile: ../reporting-management/Dockerfile
    image: reporting-management-image:latest
    environment:
      - DISCOVERY_SERVER_HOST=discovery-server
    restart: always
    depends_on:
      - discovery-server
      - app-gateway
    ports:
      - "8087:8087"
    networks:
      - ${GLOBAL_NETWORK}
