version: '1.0'

services:
  user-management:
    hostname: user-management
    build:
      context: ../user-management
      dockerfile: ../user-management/Dockerfile
    image: user-management-image:latest
    environment:
      - DISCOVERY_SERVER_HOST=discovery-server
    restart: always
    depends_on:
      - discovery-server
      - app-gateway
    ports:
      - "8085:8085"
    networks:
      - ${GLOBAL_NETWORK}
