spring:
  elasticsearch:
    uris: ${HOST_NAME:localhost}:9200
    host: ${HOST_NAME:localhost}
    port: 9200
    username: elastic
    password: 5o1NwRcarr=bpvh*kaX8
  jackson:
    default-property-inclusion: non_null
  application:
    name: PRODUCT-CATALOG
  main:
    web-application-type: reactive
  devtools:
    restart:
      enabled: true

eureka:
  client:
    service-url: { defaultZone: http://65.0.68.37:8761/eureka/ }
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
    instance-id: ${spring.application.name}:${random.value}

server:
  port: 8088

logging:
  level:
    root: info
