spring:
  devtools:
    restart:
      enabled: true
  application:
    name: shaft-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  main:
    web-application-type: reactive

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
    instance-id: ${spring.application.name}:${random.value}

logging:
  level:
    root: debug
