spring:
  devtools:
    restart:
      enabled: true
  application:
    name: shaft-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  main:
    web-application-type: reactive

server:
  port: 8080

logging:
  level:
    root: debug
