spring:
  elasticsearch:
    uris: http://localhost:9200
    host: localhost
    port: 9200
    username: elastic
    password: 5o1NwRcarr=bpvh*kaX8
  jackson:
    default-property-inclusion: non_null
  application:
    name: ACCOUNT-MANAGEMENT
  main:
    web-application-type: reactive
  devtools:
    restart:
      enabled: true

eureka:
  client:
    service-url: { defaultZone : http://localhost:8761/eureka/ }
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.application.name}:${random.value}

server:
  port: 8084

logging:
  level:
    root: info

