spring:
  elasticsearch:
    uris: ${HOST_NAME:localhost}:9200
    host: ${HOST_NAME:localhost}
    port: 9200
    username: elastic
    password: 5o1NwRcarr=bpvh*kaX8
  jackson:
    default-property-inclusion: non_null
  application:
    name: account-management
  main:
    web-application-type: reactive
  devtools:
    restart:
      enabled: true

server:
  port: 8084

logging:
  level:
    root: info

